I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/11 - room 3.rpy", line 138, in script
    call screen room3
  File "renpy/common/000statements.rpy", line 609, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "renpy/common/00action_data.rpy", line 79, in get_selected
    return __get_field(self.object, self.field, self.kind) == self.value
  File "renpy/common/00action_data.rpy", line 39, in _m1_00action_data__get_field
    raise NameError("The {} {} does not exist.".format(kind, name))
NameError: The field room does not exist.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script/11 - room 3.rpy", line 138, in script
    call screen room3
  File "E:\Development\renpy-8.0.0-sdk\renpy\ast.py", line 2232, in execute
    self.call("execute")
  File "E:\Development\renpy-8.0.0-sdk\renpy\ast.py", line 2220, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "E:\Development\renpy-8.0.0-sdk\renpy\statements.py", line 281, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 609, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "E:\Development\renpy-8.0.0-sdk\renpy\exports.py", line 3181, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "E:\Development\renpy-8.0.0-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\core.py", line 3810, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\screen.py", line 456, in visit_all
    self.child.visit_all(callback, seen=None)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\core.py", line 584, in visit_all
    callback(self)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\core.py", line 3810, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\behavior.py", line 968, in per_interact
    if self.is_selected():
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\behavior.py", line 956, in is_selected
    return is_selected(self.action)
  File "E:\Development\renpy-8.0.0-sdk\renpy\display\behavior.py", line 401, in is_selected
    return action.get_selected()
  File "renpy/common/00action_data.rpy", line 79, in get_selected
    return __get_field(self.object, self.field, self.kind) == self.value
  File "renpy/common/00action_data.rpy", line 39, in _m1_00action_data__get_field
    raise NameError("The {} {} does not exist.".format(kind, name))
NameError: The field room does not exist.

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
malViolence 1.0
Thu Mar 23 20:35:34 2023
